services:
  mysql:
    image: mysql:8.0
    container_name: game-spring-basic-assignment
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: game_spring_basic_assignment
    volumes:
      - crimson-citadel-mysql-data:/var/lib/mysql

volumes:
  crimson-citadel-mysql-data:
